### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by Krisalexroberts** [YuraSidorets/anchorfm-bot#1]
```
2020/07/20 11:32:29 open : no such file or directory
2020/07/20 11:32:29 unexpected end of JSON input
panic: unexpected end of JSON input
```
I have built using Go and entered details into config.json as per the file format, but running the script gives the above error

**Comment by YuraSidorets** [comment]
Please try to run it with the path to config as an argument "anchorfm-bot ../config/config.json"

**Comment by Krisalexroberts** [comment]
That runs now, thanks. Are you looking to put a README together?

**Comment by YuraSidorets** [comment]
Yes, I plan to update README with all the details this week.

**Comment by YuraSidorets** [comment]
README updated, I'm closing this issue.
